version: '2'

services:
  redis:
    image: redis:alpine
    volumes:
      - /srv/docker/sentry/redis:/var/lib/redis
    restart: always

  postgres:
    image: postgres:alpine
    volumes:
      - /srv/docker/sentry/postgres:/var/lib/postgresql/data
    restart: always

  www:
    build: .
    ports:
      - "8080"
    links:
      - postgres
      - redis
    volumes_from:
      - data
    entrypoint: sentry
    command: start --noinput
    env_file:
      - secrets/environment.sh
    restart: always
